library(tximport)
library(DESeq2)
library(readr)
tx2g <- read_tsv("F:/seidr_tutorial/tx2gene.tsv",col_names=c("Transcript", "Gene"))
input_files <- dir("F:/seidr_tutorial", pattern="*_quant.sf$", full.names=TRUE)
txi <- tximport(input_files, 'salmon', tx2gene=tx2g)
dummy_meta <- data.frame(N = seq_along(input_files))
dds <- DESeqDataSetFromTximport(txi, dummy_meta, ~1)
vsd <- varianceStabilizingTransformation(dds, blind=TRUE)
vst <- t(assay(vsd))
vars <- apply(vst, 2, var)
filt_id <- which(is.finite(vars))
vst <- vst[, filt_id]
medians <- apply(vst, 1, median)
vst <- sweep(vst, MARGIN=1, FUN='-', STATS=medians)
MASS::write.matrix(x=unname(vst), sep='\t', file='expression.tsv')
write(colnames(vst), file="genes.txt")